### ISSUE TITLE
Jetlime classes not resolved since 1.0.6

### ISSUE THREAD

**Issue by joreilly** [pushpalroy/jetlime#20]
I started to upgrade to 2.0.0 (had been using 1.0.3) and couldn't resolve new classes....went back and seems to have started with 1.0.6 (with existing classes used there e.g. `JetLimeItemsModel`).  Is there any new requirements in that version?

**Comment by pushpalroy** [comment]
There seems to be an issue with the AAR packaging in `2.0.0`.
It has been fixed in `2.0.1`. Thanks for pointing this out.
