### ISSUE TITLE
Add ability to set color for a custom icon and set circle background for it.

### ISSUE THREAD

**Issue by Monabr** [pushpalroy/JetLime#29]
Please make it possible.

![image](https://github.com/pushpalroy/JetLime/assets/30532666/a7e35ab2-c708-4300-83a3-0ce0c6702ae7)

**Comment by pushpalroy** [comment]
@Monabr Have you checked the `custom` function of the `EventPointType`?

It accepts a Painter, where you can pass the icon.

https://pushpalroy.github.io/JetLime/jetlime/com.pushpal.jetlime/-event-point-type/-companion/index.html#-2135258840%2FFunctions%2F-1761194290

**Comment by pushpalroy** [comment]
You can also find an example in the code:
https://github.com/pushpalroy/JetLime/blob/58d485969983030206af38b15ecd68c27400ef46/app/src/main/java/com/pushpal/jetlime/ui/timelines/CustomizedVerticalTimeLine.kt#L79

**Comment by pushpalroy** [comment]
Right. So you are looking to add a tint to your icon? And also a background in case your icon is transparent itself?

**Comment by pushpalroy** [comment]
Will be adding support for this in the next release.

**Comment by SteliosPapamichail** [comment]
@pushpalroy I could attempt to take this task on if you want :) I believe there are solutions using the painter or converting their image to a bitmap and then applying a tint but providing it directly would be much easier for end users.

**Comment by pushpalroy** [comment]
Hello @SteliosPapamichail,

Thank you for your interest in contributing to our project! I'm currently in the process of developing an enhanced method for integrating icons within the timeline, aimed at streamlining the existing implementation. If you have any ideas or suggestions on this front, I would be very keen to hear them. Your input could be incredibly valuable in refining this feature for our end users.

**Comment by pushpalroy** [comment]
The support for this has been added to the latest release `2.2.0`.

You will now be able to pass an optional `tint` color for the custom icon.
Also the `pointColor` will now act as the background for the custom icon painter.
Also, there was an issue with the custom icon animation which was fixed.

Refer: https://pushpalroy.github.io/JetLime/jetlime/com.pushpal.jetlime/-event-point-type/-companion/index.html#246472581%2FFunctions%2F-1761194290

Thanks again for using this library and providing feedback!

![custom](https://github.com/pushpalroy/JetLime/assets/19844292/718327b1-9728-43bc-bee9-81a5ee4bf08b)
