### ISSUE TITLE
Porting to Compose mutliplatform?

### ISSUE THREAD

**Issue by N7ghtm4r3** [pushpalroy/JetLime#30]
Hi, I wonder ask if it Is planned a porting to Compose Mutliplatform or will be available for Android at the Moment?

**Comment by pushpalroy** [comment]
@N7ghtm4r3 This is an Android-only library at this moment. But the plan is to support Compose multiplatform soon.

**Comment by N7ghtm4r3** [comment]
Very happy about the Compose multiplatform will be available soon!
