### ISSUE TITLE
Add support of dashed timeline for JetLimeExtendedEvent type event

### ISSUE THREAD

**Issue by N7ghtm4r3** [pushpalroy/JetLime#42]
Hi I'm using the `io.github.pushpalroy:jetlime:3.0.0` version in a `KMM` project.
I'm trying to apply the dashed effect to the line but still to be solid, may I am wrong to apply it?

Code: 

```kotlin
JetLimeColumn(
      modifier = Modifier
          .padding(
              top = it.calculateTopPadding() + 16.dp,
              start = 16.dp,
              end = 16.dp,
              bottom = it.calculateBottomPadding() + 16.dp
          ),
      itemsList = ItemsList(items),
      key = { _, item -> item.id },
      style = JetLimeDefaults.columnStyle(
          contentDistance = 24.dp,
         // is it here where to apply the dashed effect? 
          pathEffect = PathEffect.dashPathEffect(
              intervals = floatArrayOf(30f, 30f)
          )
      ),
  ) { index, mileage, position ->
      JetLimeExtendedEvent(
          style = JetLimeEventDefaults.eventStyle(
              position = position
          ),
          additionalContent = {
              // Additional content here
          }
      ) {
          // content
      }
  }
```
The result:

<img src="https://github.com/user-attachments/assets/006bff84-bf0b-4c78-a63c-7bd8770a1b01" width="350" height="700"/>

**Comment by N7ghtm4r3** [comment]
Yes for sure!

**Comment by pushpalroy** [comment]
@N7ghtm4r3 Seems like your observation is correct. 👍🏻  Currently Dashed Effect is not supported for `JetLimeExtendedEvent` type event. You can use `JetLimeEvent` for the dashed effect.

Thanks for raising this issue.

I will add support of dashed line for `JetLimeExtendedEvent` in the next patch.

**Comment by N7ghtm4r3** [comment]
Thank you for the fast reply and for the tip

**Comment by N7ghtm4r3** [comment]
> @N7ghtm4r3 The way you are applying the dashed effect is correct.
> I'm not sure why you are not being able to see the proper effect.
> 
> Can you please check the sample already added to the repo: `BasicDashedTimeLine`?

I have to check it anyway?

**Comment by pushpalroy** [comment]
@N7ghtm4r3 No need to verify anything. There is a bug due to which dashed effect is not supported in `JetLimeExtendedEvent`. I confirmed that.

You can check the sample I mentioned to use dashed effect for normal `JetLimeEvent`.

**Comment by N7ghtm4r3** [comment]
Okay thank you!

**Comment by N7ghtm4r3** [comment]
Thank you!
